### ISSUE TITLE
 Why is there no import prompt in *.vue?

### ISSUE THREAD

**Issue by jinglun2019** [lstoeferle/vite-vue2-example#10]
在*.vue文件中，为什么没有导入提示;*.ts文件里是正常的。如图。

In *.ts, import prompt  work well
![图片](https://user-images.githubusercontent.com/57926735/157818132-42e1396e-3457-4b20-8da1-e9ffdeb0a130.png)

but in *.vue,no import prompt
![图片](https://user-images.githubusercontent.com/57926735/157818254-5f669d47-2e08-4fd2-98a1-44516a183242.png)

**Comment by lstoeferle** [comment]
Hey @jinglun2019,
I'm using Webstorm as the IDE of my choice and there it's working without any issue. Since you are using VSCode you probably should consider using the [Volar](https://github.com/johnsoncodehk/volar) plugin.
