### ISSUE TITLE
Property does not exist on type '{}'

### ISSUE THREAD

**Issue by pnhuyduy** [lstoeferle/vite-vue2-example#13]
I got this error message and no IntelliSense in template tag
![image](https://user-images.githubusercontent.com/46210597/176877693-7a14a974-39d9-4979-a3b3-32c6885c3e87.png)

**Comment by lstoeferle** [comment]
Hi @pnhuyduy,
please provide a small code-snipped (e.g. of you component), else I would not be able to help you. Also it would be interesting to know which code editor you are using.

**Comment by herrmannplatz** [comment]
Guess thats related to this. https://github.com/johnsoncodehk/volar/issues/1457

**Comment by lstoeferle** [comment]
Fixed by @herrmannplatz in [this commit](https://github.com/lstoeferle/vite-vue2-windicss-starter/commit/4bcbe41a391602a997dd376fb4dd321e52cad949)

tsconfig.json
```
{
  "vueCompilerOptions": {
    "target": 2.7
  }
}
```
