### ISSUE TITLE
Env variables availability

### ISSUE THREAD

**Issue by jandante** [lstoeferle/vite-vue2-example#18]
I have a weird issue where env variables are available in my App.vue file but when importing other components for App.vue the env variables give undefined in those components.

Couldn't find anything related on SO or Google. Could it have anything to do with how it's implemented in this template?

I must say I'm new to Typescript and Vite as a whole but any tips?

Also thank you very much for this template! Already learned a ton with it!

**Comment by lstoeferle** [comment]
Hi @jandante,
thanks for your feedback :) Can you please post an example here, else I wouldn't be able to help you.

**Comment by jandante** [comment]
Sorry to waste your time. I must have done something wrong in my code. Coming back at it and trying to make simple example I see that it is working. Also in my application now.
