### ISSUE TITLE
The class of the container that wraps the Feature component is not set correctly

### ISSUE THREAD

**Issue by allenhooray** [lstoeferle/vite-vue2-example#6]
In the Commits on Mar 27, 2021（7c3c055600d5c43156ae720f0add52a62398791e）

Incorrect spacing between Feature components ( Features.vue ).

```html
      <div class="w-full py-4 pr-4 xs:pl-4 md:w-1/2 lg:w-1/4">
        <Feature
          title="vite-plugin-vue2"
          text="Vue 2 support for Vite"
          url="https://github.com/underfin/vite-plugin-vue2"
        />
      </div>
      <div class="w-full p-4 md:w-1/2 lg:w-1/4">
        <Feature
          title="vite-plugin-components"
          text="On demand components auto importing for Vite"
          url="https://github.com/antfu/vite-plugin-components"
        />
      </div>
```

I don't know if the author did it on purpose.

I guess I should write it this way——

```html
      <div class="w-full py-4 px-2 xs:pr-4 md:w-1/2 lg:w-1/4">
        <Feature
          title="vite-plugin-vue2"
          text="Vue 2 support for Vite"
          url="https://github.com/underfin/vite-plugin-vue2"
        />
      </div>
      <div class="w-full py-4 px-2 xs:pr-4 md:w-1/2 lg:w-1/4">
        <Feature
          title="vite-plugin-components"
          text="On demand components auto importing for Vite"
          url="https://github.com/antfu/vite-plugin-components"
        />
      </div>
```

**Comment by allenhooray** [comment]
Comparison before and after modification

<img width="1440" alt="截屏2021-04-30 下午1 14 30" src="https://user-images.githubusercontent.com/41528424/116651543-018b9900-a9b6-11eb-97a5-93a8a000d804.png">
<img width="1440" alt="截屏2021-04-30 下午1 14 46" src="https://user-images.githubusercontent.com/41528424/116651556-0b150100-a9b6-11eb-9e70-9186200b2646.png">

**Comment by lstoeferle** [comment]
Hi @AllenHUSH,
thanks for the hint. I will fix the styling soon, unfortunately I did not test it on large screens :)

**Comment by lstoeferle** [comment]
Should be fixed now :) See [this commit](https://github.com/lstoeferle/vite-vue2-windicss-starter/commit/206e6559d912f3fc1324671fffdca3376064f846)
